name: Train Model

on:
  workflow_dispatch:   # run manually

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
       - name: Install dependencies
          run: pip install -r correct/path/to/requirements.txt
      - name: Configure Kaggle
        run: |
          mkdir -p ~/.kaggle
          echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_KEY\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

      - name: Train model
        run: python backend/train_model.py

      - name: Commit model
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add backend/model.joblib backend/vectorizer.joblib
          git commit -m "Update trained model" || echo "No changes"
          git push
