name: Train Model

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # 3. Install dependencies (minimal, no backend/requirements.txt issue)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kaggle pandas scikit-learn joblib

      # 4. Setup Kaggle credentials
      - name: Setup Kaggle
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"${{ secrets.KAGGLE_USERNAME }}","key":"${{ secrets.KAGGLE_KEY }}"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      # ✅ 5. Test Kaggle API authentication
      - name: Test Kaggle API
        run: kaggle datasets list -s "news"

      # 6. Download dataset
      - name: Download dataset
        run: |
          kaggle datasets download -d clmentbisaillon/fake-and-real-news-dataset -p data --unzip

      # 7. Train model
      - name: Train model
        run: |
          python backend/train_model.py

      # 8. Commit & push trained model
      - name: Commit and push model
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add backend/model.joblib backend/vectorizer.joblib
          git commit -m "Update trained model" || echo "No changes to commit"
          git push

